CREATE TABLE user_account (id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(80) NOT NULL UNIQUE, email VARCHAR(160) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL);
CREATE TABLE career_profile (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL UNIQUE, school VARCHAR(120), major VARCHAR(120), grade VARCHAR(30), target_position VARCHAR(120), target_city VARCHAR(80), self_description TEXT, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT fk_profile_user FOREIGN KEY(user_id) REFERENCES user_account(id));
CREATE TABLE resume (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(500), content_type VARCHAR(100), raw_text LONGTEXT, parsed_json JSON, status VARCHAR(30) NOT NULL, is_current BOOLEAN NOT NULL DEFAULT FALSE, error_message VARCHAR(500), created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX idx_resume_user(user_id), CONSTRAINT fk_resume_user FOREIGN KEY(user_id) REFERENCES user_account(id));
CREATE TABLE skill (id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(80) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL, category VARCHAR(40) NOT NULL, aliases_json JSON);
CREATE TABLE user_skill (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, skill_id BIGINT NOT NULL, level TINYINT NOT NULL, source VARCHAR(30) NOT NULL, evidence VARCHAR(1000), source_ref_id BIGINT, confirmed BOOLEAN NOT NULL DEFAULT FALSE, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uk_user_skill_source(user_id,skill_id,source,source_ref_id), CONSTRAINT fk_us_user FOREIGN KEY(user_id) REFERENCES user_account(id), CONSTRAINT fk_us_skill FOREIGN KEY(skill_id) REFERENCES skill(id));
CREATE TABLE job_description (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, company_name VARCHAR(160), position_name VARCHAR(160) NOT NULL, raw_content LONGTEXT NOT NULL, parsed_json JSON, status VARCHAR(30) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX idx_job_user(user_id), CONSTRAINT fk_job_user FOREIGN KEY(user_id) REFERENCES user_account(id));
CREATE TABLE job_skill_requirement (id BIGINT PRIMARY KEY AUTO_INCREMENT, job_id BIGINT NOT NULL, skill_id BIGINT NOT NULL, importance VARCHAR(20) NOT NULL, requirement_level TINYINT, original_text VARCHAR(1000), UNIQUE KEY uk_job_skill(job_id,skill_id), CONSTRAINT fk_jsr_job FOREIGN KEY(job_id) REFERENCES job_description(id), CONSTRAINT fk_jsr_skill FOREIGN KEY(skill_id) REFERENCES skill(id));
CREATE TABLE conversation (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, scene VARCHAR(30) NOT NULL, title VARCHAR(160), job_id BIGINT, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX idx_conversation_user(user_id), CONSTRAINT fk_conversation_user FOREIGN KEY(user_id) REFERENCES user_account(id), CONSTRAINT fk_conversation_job FOREIGN KEY(job_id) REFERENCES job_description(id));
CREATE TABLE message (id BIGINT PRIMARY KEY AUTO_INCREMENT, conversation_id BIGINT NOT NULL, role VARCHAR(20) NOT NULL, content LONGTEXT NOT NULL, metadata_json JSON, created_at DATETIME NOT NULL, INDEX idx_message_conversation(conversation_id,created_at), CONSTRAINT fk_message_conversation FOREIGN KEY(conversation_id) REFERENCES conversation(id));
CREATE TABLE interview (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, job_id BIGINT NOT NULL, status VARCHAR(30) NOT NULL, total_score DECIMAL(5,2), report JSON, started_at DATETIME, finished_at DATETIME, CONSTRAINT fk_interview_user FOREIGN KEY(user_id) REFERENCES user_account(id), CONSTRAINT fk_interview_job FOREIGN KEY(job_id) REFERENCES job_description(id));
CREATE TABLE interview_question (id BIGINT PRIMARY KEY AUTO_INCREMENT, interview_id BIGINT NOT NULL, sequence_no INT NOT NULL, question TEXT NOT NULL, skill_id BIGINT, difficulty VARCHAR(20) NOT NULL, reference_points_json JSON, user_answer LONGTEXT, score DECIMAL(5,2), evaluation JSON, parent_question_id BIGINT, created_at DATETIME NOT NULL, INDEX idx_question_interview(interview_id,sequence_no), CONSTRAINT fk_question_interview FOREIGN KEY(interview_id) REFERENCES interview(id), CONSTRAINT fk_question_skill FOREIGN KEY(skill_id) REFERENCES skill(id));

