<script setup lang="ts">
import {ref} from 'vue'
import {useCareerStore} from '../stores/career'
const store=useCareerStore(),input=ref<HTMLInputElement>(),dragging=ref(false),notice=ref('')
async function accept(file?:File){if(!file)return;notice.value='';try{await store.uploadResume(file);notice.value='解析完成，请检查技能后确认写入画像。'}catch(e:any){notice.value=e.message}}
function choose(event:Event){accept((event.target as HTMLInputElement).files?.[0])}
function drop(event:DragEvent){dragging.value=false;accept(event.dataTransfer?.files?.[0])}
async function remove(id:number){if(window.confirm('确定删除这份简历及其技能证据吗？'))await store.deleteResume(id)}
</script>
<template><section class="workspace-page"><div class="upload-zone" :class="{dragging}" @dragover.prevent="dragging=true" @dragleave.prevent="dragging=false" @drop.prevent="drop" @click="input?.click()"><input ref="input" hidden type="file" accept=".pdf,.docx,.txt,.md" @change="choose"><span>＋</span><h2>上传你的当前简历</h2><p>拖放或选择 PDF、DOCX、TXT、Markdown，最大 8 MB</p><button class="outline-button" :disabled="store.loading">{{store.loading?'正在解析…':'选择文件'}}</button></div><p v-if="notice" class="inline-notice">{{notice}}</p><div class="section-heading"><div><p class="kicker">RESUME EVIDENCE</p><h2>结构化记录</h2></div><span>{{store.resumes.length}} 份</span></div><div v-if="store.resumes.length" class="resume-grid"><article v-for="resume in store.resumes" :key="resume.id"><div class="document-icon">DOC</div><div class="resume-copy"><span class="status-chip">{{resume.status}}</span><h3>{{resume.fileName}}</h3><p>{{resume.parsed?.skills?.map((s:any)=>s.name).join(' · ')||'等待解析'}}</p><small>{{new Date(resume.createdAt).toLocaleDateString()}}</small></div><div class="card-actions"><button v-if="resume.status==='PARSED'" class="button small" @click="store.confirmResume(resume.id)">确认证据</button><b v-else-if="resume.current">✓ 当前简历</b><button class="icon-button danger" title="删除" @click.stop="remove(resume.id)">×</button></div></article></div><div v-else class="empty-state surface"><b>尚未上传简历</b><p>仓库中的 tests/fixtures/resume-demo.md 可用于体验。</p></div></section></template>
