<script setup lang="ts">
import {computed,onMounted,ref} from 'vue'
import {api,streamUrl} from './api'
import {ElMessage} from 'element-plus'

type Tab='overview'|'profile'|'resume'|'jobs'|'chat'|'interview'
const token=ref(localStorage.getItem('career-token')||''),tab=ref<Tab>('overview'),loading=ref(false)
const auth=ref({username:'demo_student',email:'demo@career.dev',password:'career123'}),loginMode=ref(false)
const profile=ref<any>({school:'',major:'计算机科学与技术',grade:'应届生',targetPosition:'Java 后端实习',targetCity:'上海',selfDescription:''})
const skills=ref<any[]>([]),resumes=ref<any[]>([]),jobs=ref<any[]>([]),conversations=ref<any[]>([])
const jobForm=ref({companyName:'未来科技',positionName:'Java 后端实习生',rawContent:'岗位要求：熟练掌握 Java 和 Spring Boot，掌握 MySQL；了解 Redis、Linux、Docker，有良好的计算机网络基础。'}),match=ref<any>(null)
const selectedJob=ref<number|undefined>(),chatInput=ref('我适合这个岗位吗？应该优先补什么？'),chatMessages=ref<any[]>([]),conversationId=ref<number>()
const interview=ref<any>(),question=ref<any>(),answer=ref(''),report=ref<any>()
const upload=ref<HTMLInputElement>(),nav=[['overview','总览','⌂'],['profile','职业画像','◎'],['resume','简历中心','▤'],['jobs','岗位匹配','◇'],['chat','Career Agent','✦'],['interview','模拟面试','◉']] as const
const selectedJobData=computed(()=>jobs.value.find(j=>j.id===selectedJob.value))

async function run<T>(fn:()=>Promise<T>){loading.value=true;try{return await fn()}catch(e:any){ElMessage.error(e.message)}finally{loading.value=false}}
async function enter(){await run(async()=>{if(loginMode.value){const r:any=await api.post('/auth/login',{account:auth.value.username,password:auth.value.password});token.value=r.token}else{const r:any=await api.post('/auth/register',auth.value);token.value=r.token}localStorage.setItem('career-token',token.value);await refresh();ElMessage.success('欢迎进入 CareerAgent')})}
async function refresh(){const data:any=await Promise.all([api.get('/profiles/me'),api.get('/profiles/me/skills'),api.get('/resumes'),api.get('/jobs'),api.get('/conversations')]);[profile.value,skills.value,resumes.value,jobs.value,conversations.value]=data;if(!selectedJob.value&&jobs.value[0])selectedJob.value=jobs.value[0].id}
async function saveProfile(){await run(async()=>{profile.value=await api.put('/profiles/me',profile.value);ElMessage.success('画像已保存')})}
async function uploadResume(){const file=upload.value?.files?.[0];if(!file)return;await run(async()=>{const body=new FormData();body.append('file',file);let r:any=await api.post('/resumes',body);r=await api.post(`/resumes/${r.id}/parse`);await refresh();ElMessage.success(`已识别 ${r.parsed?.skills?.length||0} 项技能，请确认后写入画像`)})}
async function confirmResume(id:number){await run(async()=>{await api.post(`/resumes/${id}/confirm`);await refresh();ElMessage.success('简历证据已确认')})}
async function createJob(){await run(async()=>{const j:any=await api.post('/jobs',jobForm.value);await refresh();selectedJob.value=j.id;match.value=await api.post(`/jobs/${j.id}/match`);ElMessage.success('JD 已解析并完成匹配')})}
async function calculate(){if(!selectedJob.value)return;match.value=await run(()=>api.post(`/jobs/${selectedJob.value}/match`))}
async function ensureConversation(){if(conversationId.value)return conversationId.value;const c:any=await api.post('/conversations',{scene:'JOB_ANALYSIS',title:selectedJobData.value?.positionName||'求职咨询',jobId:selectedJob.value});conversationId.value=c.id;return c.id}
async function sendChat(){if(!chatInput.value.trim())return;const text=chatInput.value;chatMessages.value.push({role:'USER',content:text});chatInput.value='';const id=await ensureConversation();if(!id)return;const response=await fetch(streamUrl(id,text),{headers:{Authorization:`Bearer ${token.value}`}});if(!response.body)throw new Error('浏览器不支持流式响应');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',assistant={role:'ASSISTANT',content:'',status:'正在思考…',citations:[] as any[]};chatMessages.value.push(assistant);while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop()||'';for(const block of events){const name=block.match(/event:(.+)/)?.[1]?.trim();const raw=block.match(/data:(.+)/)?.[1]?.trim();if(!raw)continue;let data:any;try{data=JSON.parse(raw)}catch{data=raw}if(name==='status')assistant.status=data;if(name==='tool_call')assistant.status=`已调用 ${data.name}`;if(name==='content')assistant.content+=typeof data==='string'?data:String(data);if(name==='citation')assistant.citations.push(data);if(name==='done')assistant.status='完成'}}}
async function startInterview(){if(!selectedJob.value)return ElMessage.warning('请先选择岗位');await run(async()=>{interview.value=await api.post('/interviews',{jobId:selectedJob.value});question.value=await api.post(`/interviews/${interview.value.id}/start`);tab.value='interview'})}
async function submitAnswer(){if(!answer.value.trim())return;await run(async()=>{const r:any=await api.post(`/interviews/${interview.value.id}/answers`,{questionId:question.value.id,answer:answer.value});ElMessage.success(`本题 ${r.evaluation.score} 分：${r.evaluation.evaluation.feedback}`);answer.value='';question.value=r.nextQuestion;if(r.canFinish)await finishInterview()})}
async function finishInterview(){report.value=await api.post(`/interviews/${interview.value.id}/finish`);question.value=null}
function logout(){localStorage.removeItem('career-token');token.value='';location.reload()}
onMounted(()=>{if(token.value)refresh().catch(()=>logout())})
</script>

<template>
  <div v-if="!token" class="auth-shell">
    <section class="auth-story"><div class="brand"><span>CA</span> CareerAgent</div><div class="story-copy"><p class="eyebrow">AI CAREER COPILOT</p><h1>让每一次求职准备<br><em>都有证据可循</em></h1><p>结构化简历、确定性岗位匹配、可追溯知识检索与针对性模拟面试，构成你的完整求职闭环。</p><div class="proof"><b>5</b><span>领域工具</span><b>100%</b><span>可解释评分</span><b>M0–M5</b><span>完整闭环</span></div></div><div class="orb"></div></section>
    <section class="auth-panel"><form class="auth-card" @submit.prevent="enter"><p class="eyebrow">{{loginMode?'WELCOME BACK':'CREATE PROFILE'}}</p><h2>{{loginMode?'继续你的求职准备':'建立你的职业坐标'}}</h2><label>用户名<input v-model="auth.username" required /></label><label v-if="!loginMode">邮箱<input v-model="auth.email" type="email" required /></label><label>密码<input v-model="auth.password" type="password" minlength="6" required /></label><button class="primary" :disabled="loading">{{loading?'正在进入…':loginMode?'登录':'注册并开始'}}</button><button type="button" class="text-btn" @click="loginMode=!loginMode">{{loginMode?'没有账号？立即注册':'已有账号？直接登录'}}</button></form></section>
  </div>
  <div v-else class="app-shell">
    <aside><div class="brand"><span>CA</span> CareerAgent</div><nav><button v-for="item in nav" :key="item[0]" :class="{active:tab===item[0]}" @click="tab=item[0]"><i>{{item[2]}}</i>{{item[1]}}</button></nav><div class="aside-foot"><small>DEMO WORKSPACE</small><p>{{profile.targetPosition||'设置目标岗位'}}</p><button @click="logout">退出登录 →</button></div></aside>
    <main><header><div><p class="eyebrow">CAREER WORKSPACE</p><h1>{{nav.find(n=>n[0]===tab)?.[1]}}</h1></div><div class="header-job"><span>当前目标</span><select v-model="selectedJob"><option :value="undefined">未选择岗位</option><option v-for="j in jobs" :value="j.id">{{j.companyName}} · {{j.positionName}}</option></select></div></header>
      <section v-if="tab==='overview'" class="page"><div class="hero-card"><div><p class="eyebrow">YOUR NEXT MOVE</p><h2>{{profile.targetPosition||'定义你的目标，开始建立证据链'}}</h2><p>系统不会用模型“拍脑袋”打分。每个结论都来自你的简历证据、岗位原文或知识库资料。</p><button class="primary compact" @click="tab=jobs.length?'jobs':'profile'">{{jobs.length?'查看岗位匹配':'完善职业画像'}} →</button></div><div class="score-ring"><b>{{match?.score??'—'}}</b><span>匹配分</span></div></div><div class="metric-grid"><article><span>已确认技能</span><b>{{skills.length}}</b><small>均保留来源证据</small></article><article><span>结构化简历</span><b>{{resumes.length}}</b><small>{{resumes.filter(r=>r.status==='CONFIRMED').length}} 份已确认</small></article><article><span>目标岗位</span><b>{{jobs.length}}</b><small>可重复稳定计算</small></article></div><div class="section-title"><div><p class="eyebrow">WORKFLOW</p><h2>一条可演示的完整链路</h2></div></div><div class="steps"><div v-for="(s,i) in ['完善画像','解析简历','录入 JD','查看匹配','咨询 Agent','模拟面试']"><b>0{{i+1}}</b><span>{{s}}</span></div></div></section>
      <section v-if="tab==='profile'" class="page narrow"><div class="panel"><div class="panel-head"><div><p class="eyebrow">LONG-TERM MEMORY</p><h2>职业画像</h2></div><span class="badge">由你确认后写入</span></div><div class="form-grid"><label>学校<input v-model="profile.school" placeholder="你的学校" /></label><label>专业<input v-model="profile.major" /></label><label>年级<input v-model="profile.grade" /></label><label>目标城市<input v-model="profile.targetCity" /></label><label class="wide">目标岗位<input v-model="profile.targetPosition" /></label><label class="wide">个人简介<textarea v-model="profile.selfDescription" rows="4" placeholder="你的技术方向、项目偏好和求职目标"></textarea></label></div><button class="primary compact" @click="saveProfile">保存画像</button></div><div class="panel"><div class="panel-head"><h2>技能证据</h2><span>{{skills.length}} 条</span></div><div class="skill-list"><div v-for="s in skills"><b>{{s.name}}</b><span>Lv.{{s.level}}</span><p>{{s.evidence}}</p><small>{{s.source}} · {{s.confirmed?'已确认':'待确认'}}</small></div><div v-if="!skills.length" class="empty">确认简历后，技能证据会出现在这里。</div></div></div></section>
      <section v-if="tab==='resume'" class="page"><div class="upload-card" @click="upload?.click()"><input ref="upload" type="file" accept=".pdf,.docx,.txt,.md" hidden @change="uploadResume"/><span>＋</span><h2>上传你的当前简历</h2><p>支持 PDF / DOCX / TXT / Markdown，最大 8 MB。扫描版 PDF 暂不支持 OCR。</p><button class="secondary">选择文件</button></div><div class="cards"><article v-for="r in resumes" class="resume-card"><div><span class="badge">{{r.status}}</span><h3>{{r.fileName}}</h3><p>识别技能：{{r.parsed?.skills?.map((s:any)=>s.name).join(' · ')||'尚未解析'}}</p></div><button v-if="r.status==='PARSED'" class="primary compact" @click="confirmResume(r.id)">确认并写入画像</button><b v-else-if="r.current" class="confirmed">✓ 当前简历</b></article></div></section>
      <section v-if="tab==='jobs'" class="page split"><div class="panel"><p class="eyebrow">JOB DESCRIPTION</p><h2>录入目标岗位</h2><div class="form-grid"><label>公司<input v-model="jobForm.companyName"/></label><label>岗位<input v-model="jobForm.positionName"/></label><label class="wide">JD 原文<textarea v-model="jobForm.rawContent" rows="11"></textarea></label></div><button class="primary compact" @click="createJob">解析并计算匹配</button></div><div class="panel report"><div v-if="match"><div class="score-row"><div><p>综合技能匹配</p><b>{{match.score}}</b><span>/ 100</span></div><div><small>必需项</small><strong>{{match.requiredRate}}%</strong><small>加分项</small><strong>{{match.preferredRate}}%</strong></div></div><div class="requirements"><div v-for="d in match.details" :class="d.status.toLowerCase()"><span>{{d.skillName}}</span><b>{{d.status==='MATCHED'?'已满足':d.status==='WEAK'?'证据偏弱':'待补齐'}}</b><small>{{d.originalText}}</small></div></div></div><div v-else class="empty tall"><b>◇</b><p>选择岗位并计算后，这里会展示逐项证据与稳定评分。</p><button v-if="selectedJob" class="secondary" @click="calculate">计算当前岗位</button></div></div></section>
      <section v-if="tab==='chat'" class="page chat-page"><div class="chat-head"><div><span class="agent-mark">✦</span><div><h2>Career Agent</h2><p>{{selectedJobData?`已绑定 ${selectedJobData.companyName} · ${selectedJobData.positionName}`:'通用求职咨询'}}</p></div></div><span class="online">● READY</span></div><div class="messages"><div v-if="!chatMessages.length" class="chat-empty"><span>✦</span><h2>从一个具体问题开始</h2><p>我会按需调用画像、简历、JD、匹配与知识库工具，并显示可验证依据。</p><div><button @click="chatInput='我适合这个岗位吗？差距在哪里？'">分析岗位差距</button><button @click="chatInput='我的项目该怎么证明 Redis 能力？'">强化项目证据</button></div></div><article v-for="m in chatMessages" :class="['message',m.role.toLowerCase()]"><small>{{m.role==='USER'?'YOU':'CAREER AGENT'}} · {{m.status}}</small><p>{{m.content}}</p><div v-if="m.citations?.length" class="citations"><span v-for="c in m.citations">↗ {{c.title}} · {{c.section}}</span></div></article></div><form class="composer" @submit.prevent="sendChat"><textarea v-model="chatInput" rows="2" placeholder="询问岗位匹配、项目证据或面试准备…" @keydown.ctrl.enter="sendChat"></textarea><button class="primary">发送 ↑</button></form></section>
      <section v-if="tab==='interview'" class="page narrow"><div v-if="!interview" class="interview-start"><span>◉</span><p class="eyebrow">TARGETED INTERVIEW</p><h2>基于岗位差距的模拟技术面试</h2><p>动态出题、一次针对性追问、逐题结构化评分，并生成分技能报告。</p><button class="primary" @click="startInterview">开始模拟面试</button></div><div v-else-if="question" class="panel question"><div class="question-meta"><span>QUESTION {{String(question.sequenceNo).padStart(2,'0')}}</span><span>{{question.skillName}} · {{question.difficulty}}</span></div><h2>{{question.question}}</h2><textarea v-model="answer" rows="10" placeholder="建议按：结论 → 原理 → 项目场景 → 行动 → 可验证结果 来回答"></textarea><div class="actions"><button class="secondary" @click="finishInterview">提前结束</button><button class="primary compact" @click="submitAnswer">提交回答</button></div></div><div v-else-if="report" class="panel final-report"><p class="eyebrow">INTERVIEW REPORT</p><div class="final-score"><b>{{report.totalScore}}</b><span>综合得分</span></div><h3>优势技能</h3><p>{{report.report.strengths.join('、')||'继续积累可验证证据'}}</p><h3>薄弱技能</h3><p>{{report.report.weaknesses.join('、')||'暂无明显薄弱项'}}</p><h3>下一步建议</h3><ol><li v-for="s in report.report.suggestions">{{s}}</li></ol></div></section>
    </main>
  </div>
</template>
